---
vxlan:
  topology:
    switches:
      - name: netascode-spine1
        serial_number: 9THX258OHVK
        role: spine
        management:
          default_gateway_v4: 198.18.128.1
          management_ipv4_address: 198.18.133.201
        routing_loopback_id: 0
        vtep_loopback_id: 1
      - name: netascode-leaf1
        serial_number: 90FIJ99RAD7
        role: leaf
        management:
          default_gateway_v4: 198.18.128.1
          management_ipv4_address: 198.18.133.202
        routing_loopback_id: 0
        vtep_loopback_id: 1
      - name: netascode-border-leaf1
        serial_number: 95V91M9EDNI
        role: leaf
        management:
          default_gateway_v4: 198.18.128.1
          management_ipv4_address: 198.18.133.203
        routing_loopback_id: 0
        vtep_loopback_id: 1
      - name: netascode-border-leaf2
        serial_number: 92OM1YBTCNP
        role: leaf
        management:
          default_gateway_v4: 198.18.128.1
          management_ipv4_address: 198.18.133.204
        routing_loopback_id: 0
        vtep_loopback_id: 1
