---
vxlan:
  overlay:
    vrfs:
      - name: NaC-VRF01
        vrf_id: 150001
        vlan_id: 2001
        vrf_attach_group: all
      - name: NaC-VRF02
        vrf_id: 150002
        vlan_id: 2002
        vrf_attach_group: leaf1
      - name: NaC-VRF03
        vrf_id: 150003
        vlan_id: 2003
        vrf_attach_group: leaf2
    vrf_attach_groups:
      - name: all
        switches:
          - { hostname: netascode-border-leaf1 }
          - { hostname: netascode-border-leaf2 }
      - name: leaf1
        switches:
          - { hostname: netascode-border-leaf1 }
      - name: leaf2
        switches:
          - { hostname: netascode-border-leaf2 }

