---
vxlan:
  overlay:
    vrfs:
      - name: NaC-VRF01
        vrf_id: 150001
        vlan_id: 2001
        vrf_attach_group: vrf1_attach_group
      - name: NaC-VRF02
        vrf_id: 150002
        vlan_id: 2002
        vrf_attach_group: vrf2_attach_group
    vrf_attach_groups:
      - name: vrf1_attach_group
        switches:
          - { hostname: netascode-leaf1 }
          - { hostname: netascode-border-leaf1 }
          - { hostname: netascode-border-leaf2 }

      - name: vrf2_attach_group
        switches:
          - { hostname: netascode-leaf1 }
          - { hostname: netascode-border-leaf1 }
          - { hostname: netascode-border-leaf2 }
