---
vxlan:
  overlay_extensions:
    vrf_lites:
      - name: vrf-lite-vrf10
        vrf: NaC-VRF10
        switches:
          - name: netascode-border-leaf1
            bgp_peers:
              - address: 10.10.1.1
                remote_as: 65099
                description: BGP to dc-edge1
                address_family_ipv4_unicast:
                  send_community: true
                  send_ext_community: true
              - address: 10.10.2.2
                remote_as: 65099
                description: BGP to dc-edge2
                address_family_ipv4_unicast:
                  send_community: true
                  send_ext_community: true
